name: Build and Release with Nuitka

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: linux_x64
            nuitka_arch: x86_64
          - os: macos-latest
            artifact_name: macos_universal
            nuitka_arch: universal2
          - os: windows-latest
            artifact_name: windows_x64
            nuitka_arch: x86_64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y patchelf ccache
        
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install ccache
        
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install nuitka zstandard ordered-set
        
    - name: Build with Nuitka
      run: |
        # 创建构建目录
        mkdir -p build/${{ matrix.artifact_name }}
        
        # 设置 Nuitka 参数
        nuitka_args="--standalone --onefile --assume-yes-for-downloads"
        nuitka_args+=" --enable-plugin=tk-inter --plugin-enable=pylint-warnings"
        nuitka_args+=" --output-dir=build/${{ matrix.artifact_name }}"
        
        # 添加 macOS 特定参数
        if [ "${{ runner.os }}" = "macOS" ]; then
          nuitka_args+=" --macos-create-app-bundle"
          nuitka_args+=" --macos-app-icon=assets/icon.icns"
          nuitka_args+=" --macos-target-arch=${{ matrix.nuitka_arch }}"
        fi
        
        # 添加 Windows 特定参数
        if [ "${{ runner.os }}" = "Windows" ]; then
          nuitka_args+=" --windows-icon-from-ico=assets/icon.ico"
          nuitka_args+=" --windows-company-name=MyCompany"
          nuitka_args+=" --windows-product-name=MyApp"
        fi
        
        # 执行构建
        python -m nuitka $nuitka_args src/main.py
        
    - name: Package artifacts
      run: |
        cd build/${{ matrix.artifact_name }}
        
        # 重命名文件以包含平台信息
        if [ "${{ runner.os }}" = "Windows" ]; then
          mv main.exe ${{ matrix.artifact_name }}_app.exe
          7z a ../${{ matrix.artifact_name }}.zip ${{ matrix.artifact_name }}_app.exe
        else
          mv main ${{ matrix.artifact_name }}_app
          zip -r ../${{ matrix.artifact_name }}.zip ${{ matrix.artifact_name }}_app
        fi
        
        cd ../..
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}_build
        path: build/${{ matrix.artifact_name }}.zip
  
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Combine artifacts
      run: |
        mkdir release
        find artifacts -name '*.zip' -exec cp {} release/ \;
        
        # 创建版本说明文件
        echo "# Release Notes" > release/CHANGELOG.md
        echo "## Version ${GITHUB_REF_NAME}" >> release/CHANGELOG.md
        echo "- Built on $(date)" >> release/CHANGELOG.md
        echo "- Includes builds for Windows, macOS and Linux" >> release/CHANGELOG.md
        echo "" >> release/CHANGELOG.md
        echo "## Installation" >> release/CHANGELOG.md
        echo "Download the appropriate package for your system:" >> release/CHANGELOG.md
        echo "- Windows: windows_x64.zip" >> release/CHANGELOG.md
        echo "- macOS: macos_universal.zip" >> release/CHANGELOG.md
        echo "- Linux: linux_x64.zip" >> release/CHANGELOG.md
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body_path: release/CHANGELOG.md
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/linux_x64.zip
        asset_name: linux_x64.zip
        asset_content_type: application/zip
    
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/windows_x64.zip
        asset_name: windows_x64.zip
        asset_content_type: application/zip
    
    - name: Upload macOS Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/macos_universal.zip
        asset_name: macos_universal.zip
        asset_content_type: application/zip